name: Checkout Example

on:
  push:
    paths:
      - ".github/workflows/checkout.yml"
  workflow_dispatch:

jobs:
  checkout-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
